# Generated by Django 4.2.4 on 2023-08-10 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(blank=True, help_text='Titulo', null=True, verbose_name='Titulo')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción', null=True, verbose_name='Descripción')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(blank=True, help_text='Titulo', null=True, verbose_name='Titulo')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción', null=True, verbose_name='Descripción')),
                ('url', models.TextField(blank=True, null=True, verbose_name='URL Document')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('menu', models.ForeignKey(blank=True, help_text='Menu', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.menu', verbose_name='Menu')),
            ],
        ),
    ]
