# Generated by Django 4.2.4 on 2023-08-10 20:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(blank=True, help_text='Titulo', null=True, verbose_name='Titulo')),
                ('slug', models.CharField(blank=True, help_text='Slug', max_length=100, null=True, verbose_name='Slug')),
                ('descripcion', ckeditor.fields.RichTextField()),
                ('age', models.CharField(blank=True, help_text='Año', max_length=100, null=True, verbose_name='Año')),
                ('campo1', models.CharField(blank=True, help_text='campo1', max_length=300, null=True, verbose_name='campo1')),
                ('campo2', models.CharField(blank=True, help_text='campo2', max_length=300, null=True, verbose_name='campo2')),
                ('month', models.CharField(blank=True, help_text='redirigir', max_length=300, null=True, verbose_name='redirigir')),
                ('imagen', models.ImageField(help_text='Imagen ', upload_to='', verbose_name='Imagen ')),
                ('description', models.TextField(blank=True, help_text='Descripcion', null=True, verbose_name='Descripcion')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['id'],
            },
        ),
    ]
