# Generated by Django 4.2.4 on 2023-08-10 23:18

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_noticia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(blank=True, help_text='Titulo', null=True, verbose_name='Titulo')),
                ('slug', models.CharField(blank=True, help_text='Slug', max_length=100, null=True, verbose_name='Slug')),
                ('descripcion', ckeditor.fields.RichTextField()),
                ('imagen', models.ImageField(help_text='Imagen ', upload_to='', verbose_name='Imagen ')),
                ('description', models.TextField(blank=True, help_text='Descripcion', null=True, verbose_name='Descripcion')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(blank=True, help_text='Titulo', null=True, verbose_name='Titulo')),
                ('description', models.TextField(blank=True, help_text='Descripcion', null=True, verbose_name='Descripcion')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de contrato',
                'verbose_name_plural': 'Tipos de contratos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(blank=True, max_length=70, null=True, verbose_name='Año')),
                ('ncontrato', models.CharField(blank=True, max_length=20, null=True, verbose_name='N° de Contrato')),
                ('valor', models.CharField(blank=True, max_length=20, null=True, verbose_name='valor')),
                ('contrato', models.BooleanField(blank=True, null=True, verbose_name='Contrato')),
                ('actainicio', models.BooleanField(blank=True, null=True, verbose_name='Acta de inicio')),
                ('actafinal', models.BooleanField(blank=True, null=True, verbose_name='Acta final')),
                ('pagina', models.CharField(blank=True, max_length=70, null=True, verbose_name='pagina')),
                ('secop', models.CharField(blank=True, max_length=70, null=True, verbose_name='SECOP')),
                ('Finicio', models.CharField(blank=True, max_length=70, null=True, verbose_name='Fecha de Inicio')),
                ('Fterminacion', models.CharField(blank=True, max_length=70, null=True, verbose_name='Fecha de Terminacion')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('rup', models.TextField(blank=True, null=True, verbose_name='RUP')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tipocontrato', models.ForeignKey(blank=True, help_text='Tipo de contrato', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.tipocontrato', verbose_name='Tipo de Contrato')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['id'],
            },
        ),
    ]
