# Generated by Django 4.2.4 on 2023-08-10 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_servicio_tipocontrato_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocontrato',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='upload/documento', verbose_name='URL Document'),
        ),
    ]
